/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;


/**
 *
 * @author shrey
 */
public class addGUI extends javax.swing.JFrame {
     pPhone[] p=new pPhone[10];
     pEmail[] e=new pEmail[10];
     int np=1,yp;
     int ne=1,ye;
    /**
     * 
     * Creates new form addGUI
     */
    public addGUI() {
        initComponents();
        p[0]=pPhone1;
        e[0]=pEmail1;
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        ppName = new javax.swing.JPanel();
        lFName = new javax.swing.JLabel();
        fFName = new javax.swing.JTextField();
        lImage = new javax.swing.JLabel();
        fCompany = new javax.swing.JTextField();
        lCompany1 = new javax.swing.JLabel();
        fJobTitle = new javax.swing.JTextField();
        lJobTitle = new javax.swing.JLabel();
        fLName = new javax.swing.JTextField();
        lLName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lPhone = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pPhone1 = new main.pPhone();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        pEmail1 = new main.pEmail();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        jFileChooser1.setFileFilter(new myCustomFilter());

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 30)); // NOI18N
        jLabel1.setText("   Add Contact");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 80));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        jPanel1.setAutoscrolls(true);
        jPanel1.setPreferredSize(new java.awt.Dimension(800, 385));

        jPanel3.setPreferredSize(new java.awt.Dimension(800, 400));

        ppName.setPreferredSize(new java.awt.Dimension(800, 180));
        ppName.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lFName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lFName.setText("First Name");
        ppName.add(lFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 250, 30));

        fFName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ppName.add(fFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 250, 50));

        lImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Webp.net-resizeimage.png"))); // NOI18N
        lImage.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lImageMouseClicked(evt);
            }
        });
        lImage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lImageKeyPressed(evt);
            }
        });
        ppName.add(lImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 100, 100));

        fCompany.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ppName.add(fCompany, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 250, 50));

        lCompany1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lCompany1.setText("Company");
        ppName.add(lCompany1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 100, 250, 30));

        fJobTitle.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ppName.add(fJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 250, 50));

        lJobTitle.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lJobTitle.setText("Job Title");
        ppName.add(lJobTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 250, 30));

        fLName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        ppName.add(fLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 30, 250, 50));

        lLName.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lLName.setText("Last Name");
        ppName.add(lLName, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 0, 250, 30));

        jPanel3.add(ppName);

        jPanel2.setOpaque(false);
        jPanel2.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lPhone.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        lPhone.setText("                        Phone");
        lPhone.setPreferredSize(new java.awt.Dimension(800, 30));
        jPanel2.add(lPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 30));

        jLabel2.setPreferredSize(new java.awt.Dimension(120, 150));
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 80));

        pPhone1.setPreferredSize(new java.awt.Dimension(610, 50));
        jPanel2.add(pPhone1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, 610, 50));

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton1.setText("+");
        jButton1.setPreferredSize(new java.awt.Dimension(50, 50));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 50, 50));

        jPanel3.add(jPanel2);

        jPanel4.setPreferredSize(new java.awt.Dimension(800, 80));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jLabel3.setText("Email");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 0, 250, 30));
        jPanel4.add(pEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 30, -1, -1));

        jButton2.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton2.setText("+");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 30, 50, 50));

        jPanel3.add(jPanel4);

        jPanel1.add(jPanel3);

        jScrollPane1.setViewportView(jPanel1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 850, 400));

        jButton3.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton3.setText("Cancel");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 480, 100, 50));

        jButton4.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        jButton4.setText("Save");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 480, 100, 50));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
     p[np]=new pPhone();
     yp=np*60;
     jPanel2.add(p[np],new org.netbeans.lib.awtextra.AbsoluteConstraints(120, p[0].getY()+(yp), -1, -1));
     Dimension d1=new Dimension(800,jPanel2.getHeight()+60);     
     Dimension d2=new Dimension(800,jPanel3.getHeight()+60);     
     jPanel2.setPreferredSize(d1);
     jPanel3.setPreferredSize(d2);
     jPanel1.setPreferredSize(d2);
     np++;
     if(np>9)jButton1.setEnabled(false);
     
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     e[ne]=new pEmail();
     ye=ne*60;
     jPanel4.add(e[ne],new org.netbeans.lib.awtextra.AbsoluteConstraints(120, e[0].getY()+(ye), -1, -1));
     Dimension d1=new Dimension(800,jPanel4.getHeight()+60);     
     Dimension d2=new Dimension(800,jPanel3.getHeight()+60);     
     jPanel4.setPreferredSize(d1);
     jPanel3.setPreferredSize(d2);
     jPanel1.setPreferredSize(d2);
     ne++;
     if(ne>9)jButton2.setEnabled(false);
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
     this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
     String name="",job="",email="",phone="",image="";
     try{
     name=fFName.getText()+" \n";}
     catch(Exception e1){
         
     }
     try{
     job=fCompany.getText()+" \n";}
     catch(Exception e1){
         
     }
     try{
     name+=fLName.getText();}
     catch(Exception e1){
         name+=" ";
     }
     try{
     job+=fJobTitle.getText();}
     catch(Exception e1){
         job+=" ";
     }
     try{
     for(int i=0;i<10;i++){
     phone+=p[i].fCode.getText().trim()+"-"+p[i].fNumber.getText()+"-"+p[i].fPType.getSelectedItem()+"\n";}
     }
     catch(Exception e1){
     }
     try{
     for(int i=0;i<10;i++){
     email+=e[i].fEmail.getText()+"-"+e[i].fEType.getSelectedItem()+"\n";}
     }
     catch(Exception e1){
     }
     image=lImage.getIcon().toString().substring(5);
     if("/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png".equals(image))image=null;
     try{
         Class.forName("com.mysql.jdbc.Driver");
         Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book","root","shrey");
         Statement stmt=con.createStatement();  
         String query="Insert into contact values('"+name+"','"+job+"','"+phone+"','"+email+"','"+image+"')";
         stmt.executeUpdate(query);}
     catch(ClassNotFoundException | SQLException e2){
     System.out.print(e2);}
     this.dispose();
     
    }//GEN-LAST:event_jButton4ActionPerformed

    private void lImageKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lImageKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_lImageKeyPressed

    private void lImageMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lImageMouseClicked
      int returnVal=jFileChooser1.showOpenDialog(this);
      String path;
      if(returnVal==JFileChooser.APPROVE_OPTION)
     path=jFileChooser1.getSelectedFile().getAbsolutePath();
      else path="/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png";
     ImageIcon icon=new ImageIcon(path);
     icon.getImage().flush();        
      lImage.setIcon(icon);
      System.out.println(lImage.getIcon().toString());
      // TODO add your handling code here:
    }//GEN-LAST:event_lImageMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(addGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(addGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(addGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(addGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new addGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField fCompany;
    private javax.swing.JTextField fFName;
    private javax.swing.JTextField fJobTitle;
    private javax.swing.JTextField fLName;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lCompany1;
    private javax.swing.JLabel lFName;
    private javax.swing.JLabel lImage;
    private javax.swing.JLabel lJobTitle;
    private javax.swing.JLabel lLName;
    private javax.swing.JLabel lPhone;
    private main.pEmail pEmail1;
    private main.pPhone pPhone1;
    private javax.swing.JPanel ppName;
    // End of variables declaration//GEN-END:variables
}
