/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Dimension;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.ImageIcon;

/**
 *
 * @author shrey
 */
public class homeGUI extends javax.swing.JFrame {
   display[] d1;
   int count1;
    /**
     * Creates new form homeGUI
     */
    public homeGUI() {
        initComponents();
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="SELECT COUNT(*) as total from contact;";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next())count1=rs.getInt("total");
        }
        catch(Exception e){}
        d1=new display[count1];
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bSearch = new javax.swing.JButton();
        fSearch = new javax.swing.JTextField();
        bAddContact = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lTop = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayPanel = new javax.swing.JPanel();
        displayInternal = new javax.swing.JPanel();
        bRefresh = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Address Book");
        setPreferredSize(new java.awt.Dimension(1500, 800));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bSearch.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        bSearch.setText("Search");
        bSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSearchActionPerformed(evt);
            }
        });
        getContentPane().add(bSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 10, 150, 60));

        fSearch.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        fSearch.setToolTipText("");
        fSearch.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                fSearchCaretUpdate(evt);
            }
        });
        getContentPane().add(fSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 10, 750, 60));

        bAddContact.setBackground(new java.awt.Color(244, 19, 19));
        bAddContact.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        bAddContact.setForeground(new java.awt.Color(255, 255, 255));
        bAddContact.setText("Add Contact");
        bAddContact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bAddContactActionPerformed(evt);
            }
        });
        getContentPane().add(bAddContact, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 250, 80));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 250, 530));

        lTop.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/top.png"))); // NOI18N
        getContentPane().add(lTop, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1500, 80));

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        displayPanel.setAlignmentX(0.0F);
        displayPanel.setAlignmentY(0.0F);

        displayInternal.setAlignmentX(0.0F);
        displayInternal.setAlignmentY(0.0F);
        displayInternal.setPreferredSize(new java.awt.Dimension(1230, 720));
        displayPanel.add(displayInternal);

        jScrollPane1.setViewportView(displayPanel);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 80, 1250, 720));

        bRefresh.setBackground(new java.awt.Color(244, 19, 19));
        bRefresh.setFont(new java.awt.Font("Ubuntu", 0, 25)); // NOI18N
        bRefresh.setForeground(new java.awt.Color(255, 255, 255));
        bRefresh.setText("Refresh");
        bRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bRefreshActionPerformed(evt);
            }
        });
        getContentPane().add(bRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 160, 250, 80));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void bAddContactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bAddContactActionPerformed
     addGUI ag=new addGUI();ag.setVisible(true);  // TODO add your handling code here:
    }//GEN-LAST:event_bAddContactActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="Select * from contact order by name";
        ResultSet rs=stmt.executeQuery(query);
        int i=0;
        while(rs.next()){
        d1[i]=new display();
        displayInternal.add(d1[i]);
        d1[i].lName.setText("  "+rs.getString("Name").substring(0,1).toUpperCase()+rs.getString("Name").substring(1));
        String displayphone=rs.getString("phone"),tempdp;
        tempdp=displayphone.substring(displayphone.indexOf("-")+1);
        displayphone=displayphone.substring(0,tempdp.indexOf("-")+displayphone.indexOf("-")+1);
        d1[i].lPhone.setText(displayphone);
        String displayemail=rs.getString("email"),tempde;
        tempde=displayemail.substring(0,displayemail.indexOf("\n"));
        displayemail=displayemail.substring(0,tempde.lastIndexOf("-"));
        d1[i].lEmail.setText(displayemail);
        String displaycompany=rs.getString("job");
        displaycompany=displaycompany.substring(0,displaycompany.indexOf("\n"));
        d1[i].lCompany.setText(displaycompany);
        String path=rs.getString("image");
             ImageIcon icon;
             if(path==null){
             path="/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png";
             }
             if(path.startsWith("/home/home")){
             path=path.substring(5);
             }
             if(path.startsWith("/home"))path=path;
             else path="/home"+path;
             
             while(path.contains("%20"))
             path=path.substring(0,path.indexOf("%20"))+" "+path.substring(path.indexOf("%20")+3);
             System.out.println(path);
             icon=new ImageIcon(path);
             icon.getImage().flush();
             d1[i].lImage.setIcon(icon);        
        i++;
        if(i>9){
            Dimension d1= new Dimension(1230,(count1+1)*75);
            displayPanel.setPreferredSize(d1);
            displayInternal.setPreferredSize(d1);
        }
        }
       }catch(ClassNotFoundException | SQLException e2){}
       count1=0;
       // TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void bRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bRefreshActionPerformed
        displayInternal.removeAll();
        displayInternal.revalidate();
        displayInternal.repaint();
        d1=null;
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="SELECT COUNT(*) as total from contact;";
        ResultSet rs=stmt.executeQuery(query);
        if(rs.next())count1=rs.getInt("total");
        }
        catch(Exception e2){}
        d1=new display[count1];
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="Select * from contact order by name";
        ResultSet rs=stmt.executeQuery(query);
        int i=0;
        while(rs.next()){
        d1[i]=new display();
        displayInternal.add(d1[i]);
        d1[i].lName.setText("  "+rs.getString("Name").substring(0,1).toUpperCase()+rs.getString("Name").substring(1));
        String displayphone=rs.getString("phone"),tempdp;
        tempdp=displayphone.substring(displayphone.indexOf("-")+1);
        displayphone=displayphone.substring(0,tempdp.indexOf("-")+displayphone.indexOf("-")+1);
        d1[i].lPhone.setText(displayphone);
        String displayemail=rs.getString("email"),tempde;
        tempde=displayemail.substring(0,displayemail.indexOf("\n"));
        displayemail=displayemail.substring(0,tempde.lastIndexOf("-"));
        d1[i].lEmail.setText(displayemail);
        String displaycompany=rs.getString("job");
        displaycompany=displaycompany.substring(0,displaycompany.indexOf("\n"));
        d1[i].lCompany.setText(displaycompany);
        String path=rs.getString("image");
             ImageIcon icon;
             if(path==null){
             path="/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png";
             }
             if(path.startsWith("/home/home")){
             path=path.substring(5);
             }
             if(path.startsWith("/home"))path=path;
             else path="/home"+path;
             
             while(path.contains("%20"))
             path=path.substring(0,path.indexOf("%20"))+" "+path.substring(path.indexOf("%20")+3);
             System.out.println(path);
             icon=new ImageIcon(path);
             icon.getImage().flush();
             d1[i].lImage.setIcon(icon);        
        i++;
        if(i>9){
            Dimension d1= new Dimension(1230,(count1+1)*75);
            displayPanel.setPreferredSize(d1);
            displayInternal.setPreferredSize(d1);
        }
        
        }
       }catch(ClassNotFoundException | SQLException e2){} 
        fSearch.setText("");// TODO add your handling code here:
    }//GEN-LAST:event_bRefreshActionPerformed

    private void fSearchCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_fSearchCaretUpdate
        displayInternal.removeAll();
        displayInternal.revalidate();
        displayInternal.repaint();
        d1=null;        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="SELECT COUNT(*) as total from contact where name like '%"+fSearch.getText()+"%';";
        ResultSet rs1=stmt.executeQuery(query);
        if(rs1.next())count1=rs1.getInt("total");
        }
        catch(Exception e){}
        d1=new display[count1];
             
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="Select * from contact where name like '%"+fSearch.getText()+"%' order by name ;";
        ResultSet rs=stmt.executeQuery(query);
        int i=0;
        while(rs.next()){
        d1[i]=new display();
        displayInternal.add(d1[i]);
        d1[i].lName.setText("  "+rs.getString("Name").substring(0,1).toUpperCase()+rs.getString("Name").substring(1));
        String displayphone=rs.getString("phone"),tempdp;
        tempdp=displayphone.substring(displayphone.indexOf("-")+1);
        displayphone=displayphone.substring(0,tempdp.indexOf("-")+displayphone.indexOf("-")+1);
        d1[i].lPhone.setText(displayphone);
        String displayemail=rs.getString("email"),tempde;
        tempde=displayemail.substring(0,displayemail.indexOf("\n"));
        displayemail=displayemail.substring(0,tempde.lastIndexOf("-"));
        d1[i].lEmail.setText(displayemail);
        String displaycompany=rs.getString("job");
        displaycompany=displaycompany.substring(0,displaycompany.indexOf("\n"));
        d1[i].lCompany.setText(displaycompany);
        String path=rs.getString("image");
             ImageIcon icon;
             if(path==null){
             path="/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png";
             }
             if(path.startsWith("/home/home")){
             path=path.substring(5);
             }
             if(path.startsWith("/home"))path=path;
             else path="/home"+path;
             
             while(path.contains("%20"))
             path=path.substring(0,path.indexOf("%20"))+" "+path.substring(path.indexOf("%20")+3);
             System.out.println(path);
             icon=new ImageIcon(path);
             icon.getImage().flush();
             d1[i].lImage.setIcon(icon);        
        i++;
        if(i>9){
            Dimension d1= new Dimension(1230,(count1+1)*75);
            displayPanel.setPreferredSize(d1);
            displayInternal.setPreferredSize(d1);
        }
        }
       }catch(ClassNotFoundException | SQLException e2){}       // TODO add your handling code here:
    }//GEN-LAST:event_fSearchCaretUpdate

    private void bSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSearchActionPerformed
        displayInternal.removeAll();
        displayInternal.revalidate();
        displayInternal.repaint();
        d1=null;        
        try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="SELECT COUNT(*) as total from contact where name like '%"+fSearch.getText()+"%';";
        ResultSet rs1=stmt.executeQuery(query);
        if(rs1.next())count1=rs1.getInt("total");
        }
        catch(Exception e){}
        d1=new display[count1];
       try{
        Class.forName("com.mysql.jdbc.Driver");
        Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/address_book", "root", "shrey");
        Statement stmt=con.createStatement();
        String query="Select * from contact where name like '%"+fSearch.getText()+"%' order by name ;";
        ResultSet rs=stmt.executeQuery(query);
        int i=0;
        while(rs.next()){
        d1[i]=new display();
        displayInternal.add(d1[i]);
        d1[i].lName.setText("  "+rs.getString("Name").substring(0,1).toUpperCase()+rs.getString("Name").substring(1));
        String displayphone=rs.getString("phone"),tempdp;
        tempdp=displayphone.substring(displayphone.indexOf("-")+1);
        displayphone=displayphone.substring(0,tempdp.indexOf("-")+displayphone.indexOf("-")+1);
        d1[i].lPhone.setText(displayphone);
        String displayemail=rs.getString("email"),tempde;
        tempde=displayemail.substring(0,displayemail.indexOf("\n"));
        displayemail=displayemail.substring(0,tempde.lastIndexOf("-"));
        d1[i].lEmail.setText(displayemail);
        String displaycompany=rs.getString("job");
        displaycompany=displaycompany.substring(0,displaycompany.indexOf("\n"));
        d1[i].lCompany.setText(displaycompany);
        String path=rs.getString("image");
             ImageIcon icon;
             if(path==null){
             path="/home/shrey/NetBeansProjects/Address Book/src/main/Webp.net-resizeimage.png";
             }
             if(path.startsWith("/home/home")){
             path=path.substring(5);
             }
             if(path.startsWith("/home"))path=path;
             else path="/home"+path;
             
             while(path.contains("%20"))
             path=path.substring(0,path.indexOf("%20"))+" "+path.substring(path.indexOf("%20")+3);
             System.out.println(path);
             icon=new ImageIcon(path);
             icon.getImage().flush();
             d1[i].lImage.setIcon(icon);        
        i++;
        if(i>9){
            Dimension d1= new Dimension(1230,(count1+1)*75);
            displayPanel.setPreferredSize(d1);
            displayInternal.setPreferredSize(d1);
        }
        }
       }catch(ClassNotFoundException | SQLException e2){}   // TODO add your handling code here:
    }//GEN-LAST:event_bSearchActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAddContact;
    private javax.swing.JButton bRefresh;
    private javax.swing.JButton bSearch;
    private javax.swing.JPanel displayInternal;
    private javax.swing.JPanel displayPanel;
    private javax.swing.JTextField fSearch;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lTop;
    // End of variables declaration//GEN-END:variables
}
