package main;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author shrey
 */
public class pEmail extends javax.swing.JPanel {

    /**
     * Creates new form pEmail
     */
    public pEmail() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fEType = new javax.swing.JComboBox<>();
        fEmail = new javax.swing.JTextField();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        fEType.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        fEType.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Main", "Mobile", "Office", "Work", "Personal" }));
        fEType.setName(""); // NOI18N
        add(fEType, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 0, 250, 50));

        fEmail.setFont(new java.awt.Font("Ubuntu", 0, 20)); // NOI18N
        add(fEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 50));
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> fEType;
    public javax.swing.JTextField fEmail;
    // End of variables declaration//GEN-END:variables
}
